fixed reading file without external storage, added reading file from …
kivy/plyer pull request #611
Opened 2021-03-26 06:07 UTC by kengoon

2021-05-28 17:17 UTC, akshayaurora requested changes

2021-05-30 07:54 UTC, kengoon commented on plyer/platforms/android/email.py
> +
ok

2021-05-30 08:41 UTC, kengoon commented on plyer/platforms/android/email.py
> +
I tried reverting the commit and it seems I can't make a new PR. I don't really know how to do that

2021-05-31 16:56 UTC, akshayaurora commented
Don't worry about it. Will cherry pick earlier commits and remove the irrelevant part.

2021-06-02 11:15 UTC, akshayaurora commented
@kengoon thanks!

2021-06-02 11:15 UTC, closed without merging