Clear documentation for Processors
kivy/plyer pull request #689
Opened 2022-07-04 20:44 UTC by rshah713

Updated README + docstring

2022-07-10 15:32 UTC, misl6 commented
Hi @rshah713 !

Seems that the `Continuous Integration with Ubuntu / style` is failing, can you take care of the failures related to this PR?

2022-07-10 15:33 UTC, misl6 requested changes
Seems that the `Continuous Integration with Ubuntu / style` test is failing, can you take care of the failures related to this PR?

2022-07-11 01:50 UTC, rshah713 commented
Thanks for the comment @misl6! Most recent commits have all tests passing, feel free to merge

2022-07-11 17:18 UTC, misl6 requested changes
⚠️ Looks like we deprecated `processors` via #483.

2022-07-11 17:18 UTC, misl6 commented on plyer/platforms/linux/notification.py
> +            "{'title': <'" + title + "'>, 'body': <'" + body + "'>}"
That looks fine on latest `master`, can you rebase on top of it?

2022-07-11 17:18 UTC, misl6 commented on README.md
> +| Processors                     |         |     |         |      | ✔     |
`processor` was present in this list prior to https://github.com/kivy/plyer/pull/483.

`processor` is now deprecated in favor of `cpu`, so I don't feel that should be in this list.

2022-07-11 17:18 UTC, misl6 commented on plyer/facades/processors.py
> +processors in a system
Maybe we should also add a deprecation notice? (We lost our chance to remove `processor` before release `2.0.0`)

2022-07-11 20:40 UTC, rshah713 commented
Just fixed the requested changes @misl6, let me know if there is anything else

2022-07-13 18:19 UTC, misl6 approved these changes
Thank you! LGTM.

2022-07-13 18:19 UTC, merged