Make doc structure consistent and up-to-date
kivy/plyer pull request #786
Opened 2023-11-26 09:57 UTC by Julian-O

This is part of an effort to make the Kivy sibling projects' documentation
structure consistent and up-to-date.

Unrelated changes:
* Readme Copy-edit. Reformat markdown table
* RST added structure, including API page
* Congrats, promoted from "beta" to "stable".
* Fixed some (but not all) unrelated PEP8 changes

CHECKLIST

* CONTRIBUTING.md
   [x] If repo takes user contributions, is present
   [x] In root dir (not .github dir)
   [x] Refers to kivy/kivy Contribution Guidelines.
   
* LICENSE
   [x] If repo takes user contributions, is present.
   [x] Acknowledges the range of years to 2023.
   [x] Acknowledges Kivy Team and other contributors
   [x] Mentions it is an MIT License.
   
* CODE_OF_CONDUCT.md
   [x] If repo takes user contributions or hosts discussions, is present.
   [x] Refers to kivy/kivy CODE_OF_CONDUCT.md
   
* CONTACT.md
   [x] Refers to kivy/kivy CONTACT.md

* FAQ.md
   [NA] If repo is big enough for RST documentation, is present.
   (RST documentation exists but is trivial)
   
* README:
   [x] Is a Markdown file.
   [x] Describes the project.
   [x] Describes its place in the Kivy sibling projects.
   [x] If CONTRIBUTING exists, mentions it.
   [x] If LICENSE exists, mentions it.
   [x] If CODE_OF_CONDUCT exists, mentions it.
   [x] Mentions kivy/kivy CONTACT.md
   [NA] Uses Python syntax colouring for embedded Python code.
   [x] Uses badges to display current status.

* RST documentation, if present
   [x] Describes the project.
   [x] Describes its place in the Kivy sibling projects.
   [x] Mentions LICENSE.
   [x] Mentions CONTRIBUTING
   [NA] Mentions FAQ
   [x] conf.py mentioned Kivy Team and other contributors
		- copyright, latex_documents, man_pages, texinfo documents
   
* WORKFLOWS
   [x] NO_RESPONSE.yml is present if the repo has awaiting_reply tag.
   [x] NO_RESPONSE uses latest script versions.
   [x] SUPPORT.yml is present if the repo has a `support` tag.
   [x] SUPPORT.yml refers to kivy/kivy CONTACT.md

* setup.py/cfg, if present and on PyPI
   [x] Supplies description to PyPI
   [x] Supplies Python versions to PyPI
   [x] Supplies Documentation, if any, to PyPI

2023-12-06 20:03 UTC, misl6 requested changes
Hi @Julian-O !

I've left some comments, let me know what you think about it.

2023-12-06 20:03 UTC, misl6 commented on docs/source/index.rst
> +of various hardware platforms, especially Android and iOS devices.
```suggestion
Plyer is a platform-independent Python API for accessing features
of various platforms (Android, iOS, macOS, Linux and Windows).
```

2023-12-06 20:03 UTC, misl6 commented on docs/source/index.rst
> +`latest license <https://github.com/kivy/kivy/blob/master/LICENSE>`_
```suggestion
`latest license <https://github.com/kivy/plyer/blob/master/LICENSE>`_
```

2023-12-06 20:03 UTC, misl6 commented on setup.py
> +                'various hardware platforms, especially Android and iOS '
Maybe the same description (for SEO purposes) that I have suggested in README?

2023-12-07 03:50 UTC, Julian-O commented on README.md
> +of various hardware platforms, especially Android and iOS devices.
Okay, but I have reworded to keep in the hardware part, because that is the element that unifies these APIs.

2023-12-07 17:40 UTC, merged